### ISSUE TITLE
install

### ISSUE THREAD

**Issue by malekdahmeni1** [maximgorbatyuk/net-blank-app#7]
hello .can you plz explain how to install to my computer .thank you

**Comment by maximgorbatyuk** [comment]
Hello.

1. Install .net core 3.1 SDK and .net 5 SDK both
2. Install Node.js
3. Install Angular CLI
4. Clone the project
5. Go to src folder
6. Open the solution file (*.sln) with Visual Studio IDE (install it if you don't have it). IN the IDe backend apps would be opened
7. Run both the applications
8. Go to /src/Frontend folder
9. Open the folder with any Web IDe or Visual Studio Code
10. Open terminal app (bash / powershell / windows terminal)
11. Install all the dependencies by `npm install`
12. Launch the Angular app by `ng serve` command
